package Vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 게시글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Board implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시글 번호. */
	private Integer bno;

	/** 게시글 제목. */
	private String btitle;

	/** 게시글 내용. */
	private String bcontent;

	/** 게시글 등록일. */
	private Date brdate;

	/** 게시글 조회수. */
	private Integer bhit;

	/** 카테고리. */
	private String btype;

	/** 회원정보. */
	private Member member;

	/** 지역 댓글 목록. */
	private Set<Reply> replySet;

	/** 게시글 첨부파일 목록. */
	private Set<Uploadfile> uploadfileSet;

	/**
	 * 생성자.
	 */
	public Board() {
		this.replySet = new HashSet<Reply>();
		this.uploadfileSet = new HashSet<Uploadfile>();
	}

	/**
	 * 게시글 번호을 설정합니다..
	 * 
	 * @param bno
	 *            게시글 번호
	 */
	public void setBno(Integer bno) {
		this.bno = bno;
	}

	/**
	 * 게시글 번호을 가져옵니다..
	 * 
	 * @return 게시글 번호
	 */
	public Integer getBno() {
		return this.bno;
	}

	/**
	 * 게시글 제목을 설정합니다..
	 * 
	 * @param btitle
	 *            게시글 제목
	 */
	public void setBtitle(String btitle) {
		this.btitle = btitle;
	}

	/**
	 * 게시글 제목을 가져옵니다..
	 * 
	 * @return 게시글 제목
	 */
	public String getBtitle() {
		return this.btitle;
	}

	/**
	 * 게시글 내용을 설정합니다..
	 * 
	 * @param bcontent
	 *            게시글 내용
	 */
	public void setBcontent(String bcontent) {
		this.bcontent = bcontent;
	}

	/**
	 * 게시글 내용을 가져옵니다..
	 * 
	 * @return 게시글 내용
	 */
	public String getBcontent() {
		return this.bcontent;
	}

	/**
	 * 게시글 등록일을 설정합니다..
	 * 
	 * @param brdate
	 *            게시글 등록일
	 */
	public void setBrdate(Date brdate) {
		this.brdate = brdate;
	}

	/**
	 * 게시글 등록일을 가져옵니다..
	 * 
	 * @return 게시글 등록일
	 */
	public Date getBrdate() {
		return this.brdate;
	}

	/**
	 * 게시글 조회수을 설정합니다..
	 * 
	 * @param bhit
	 *            게시글 조회수
	 */
	public void setBhit(Integer bhit) {
		this.bhit = bhit;
	}

	/**
	 * 게시글 조회수을 가져옵니다..
	 * 
	 * @return 게시글 조회수
	 */
	public Integer getBhit() {
		return this.bhit;
	}

	/**
	 * 카테고리을 설정합니다..
	 * 
	 * @param btype
	 *            카테고리
	 */
	public void setBtype(String btype) {
		this.btype = btype;
	}

	/**
	 * 카테고리을 가져옵니다..
	 * 
	 * @return 카테고리
	 */
	public String getBtype() {
		return this.btype;
	}

	/**
	 * 회원정보을 설정합니다..
	 * 
	 * @param member
	 *            회원정보
	 */
	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 회원정보을 가져옵니다..
	 * 
	 * @return 회원정보
	 */
	public Member getMember() {
		return this.member;
	}

	/**
	 * 지역 댓글 목록을 설정합니다..
	 * 
	 * @param replySet
	 *            지역 댓글 목록
	 */
	public void setReplySet(Set<Reply> replySet) {
		this.replySet = replySet;
	}

	/**
	 * 지역 댓글를 추가합니다..
	 * 
	 * @param reply
	 *            지역 댓글
	 */
	public void addReply(Reply reply) {
		this.replySet.add(reply);
	}

	/**
	 * 지역 댓글 목록을 가져옵니다..
	 * 
	 * @return 지역 댓글 목록
	 */
	public Set<Reply> getReplySet() {
		return this.replySet;
	}

	/**
	 * 게시글 첨부파일 목록을 설정합니다..
	 * 
	 * @param uploadfileSet
	 *            게시글 첨부파일 목록
	 */
	public void setUploadfileSet(Set<Uploadfile> uploadfileSet) {
		this.uploadfileSet = uploadfileSet;
	}

	/**
	 * 게시글 첨부파일를 추가합니다..
	 * 
	 * @param uploadfile
	 *            게시글 첨부파일
	 */
	public void addUploadfile(Uploadfile uploadfile) {
		this.uploadfileSet.add(uploadfile);
	}

	/**
	 * 게시글 첨부파일 목록을 가져옵니다..
	 * 
	 * @return 게시글 첨부파일 목록
	 */
	public Set<Uploadfile> getUploadfileSet() {
		return this.uploadfileSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bno == null) ? 0 : bno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Board other = (Board) obj;
		if (bno == null) {
			if (other.bno != null) {
				return false;
			}
		} else if (!bno.equals(other.bno)) {
			return false;
		}
		return true;
	}

}
