package Vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 회원정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Member implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회원번호. */
	private Integer mno;

	/** 아이디. */
	private String mid;

	/** 비밀번호. */
	private String mpw;

	/** 닉네임. */
	private String mnicknm;

	/** 이름. */
	private String mname;

	/** 생년월일. */
	private Integer mbirth;

	/** 연락처. */
	private String mphone;

	/** 성별. */
	private String mgender;

	/** 이메일. */
	private String memail;

	/** 회원가입일. */
	private Date mrdate;

	/** 게시글 목록. */
	private Set<Board> boardSet;

	/** 지역 댓글 목록. */
	private Set<Reply> replySet;

	/**
	 * 생성자.
	 */
	public Member() {
		this.boardSet = new HashSet<Board>();
		this.replySet = new HashSet<Reply>();
	}

	/**
	 * 회원번호을 설정합니다..
	 * 
	 * @param mno
	 *            회원번호
	 */
	public void setMno(Integer mno) {
		this.mno = mno;
	}

	/**
	 * 회원번호을 가져옵니다..
	 * 
	 * @return 회원번호
	 */
	public Integer getMno() {
		return this.mno;
	}

	/**
	 * 아이디을 설정합니다..
	 * 
	 * @param mid
	 *            아이디
	 */
	public void setMid(String mid) {
		this.mid = mid;
	}

	/**
	 * 아이디을 가져옵니다..
	 * 
	 * @return 아이디
	 */
	public String getMid() {
		return this.mid;
	}

	/**
	 * 비밀번호을 설정합니다..
	 * 
	 * @param mpw
	 *            비밀번호
	 */
	public void setMpw(String mpw) {
		this.mpw = mpw;
	}

	/**
	 * 비밀번호을 가져옵니다..
	 * 
	 * @return 비밀번호
	 */
	public String getMpw() {
		return this.mpw;
	}

	/**
	 * 닉네임을 설정합니다..
	 * 
	 * @param mnicknm
	 *            닉네임
	 */
	public void setMnicknm(String mnicknm) {
		this.mnicknm = mnicknm;
	}

	/**
	 * 닉네임을 가져옵니다..
	 * 
	 * @return 닉네임
	 */
	public String getMnicknm() {
		return this.mnicknm;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param mname
	 *            이름
	 */
	public void setMname(String mname) {
		this.mname = mname;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getMname() {
		return this.mname;
	}

	/**
	 * 생년월일을 설정합니다..
	 * 
	 * @param mbirth
	 *            생년월일
	 */
	public void setMbirth(Integer mbirth) {
		this.mbirth = mbirth;
	}

	/**
	 * 생년월일을 가져옵니다..
	 * 
	 * @return 생년월일
	 */
	public Integer getMbirth() {
		return this.mbirth;
	}

	/**
	 * 연락처을 설정합니다..
	 * 
	 * @param mphone
	 *            연락처
	 */
	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	/**
	 * 연락처을 가져옵니다..
	 * 
	 * @return 연락처
	 */
	public String getMphone() {
		return this.mphone;
	}

	/**
	 * 성별을 설정합니다..
	 * 
	 * @param mgender
	 *            성별
	 */
	public void setMgender(String mgender) {
		this.mgender = mgender;
	}

	/**
	 * 성별을 가져옵니다..
	 * 
	 * @return 성별
	 */
	public String getMgender() {
		return this.mgender;
	}

	/**
	 * 이메일을 설정합니다..
	 * 
	 * @param memail
	 *            이메일
	 */
	public void setMemail(String memail) {
		this.memail = memail;
	}

	/**
	 * 이메일을 가져옵니다..
	 * 
	 * @return 이메일
	 */
	public String getMemail() {
		return this.memail;
	}

	/**
	 * 회원가입일을 설정합니다..
	 * 
	 * @param mrdate
	 *            회원가입일
	 */
	public void setMrdate(Date mrdate) {
		this.mrdate = mrdate;
	}

	/**
	 * 회원가입일을 가져옵니다..
	 * 
	 * @return 회원가입일
	 */
	public Date getMrdate() {
		return this.mrdate;
	}

	/**
	 * 게시글 목록을 설정합니다..
	 * 
	 * @param boardSet
	 *            게시글 목록
	 */
	public void setBoardSet(Set<Board> boardSet) {
		this.boardSet = boardSet;
	}

	/**
	 * 게시글를 추가합니다..
	 * 
	 * @param board
	 *            게시글
	 */
	public void addBoard(Board board) {
		this.boardSet.add(board);
	}

	/**
	 * 게시글 목록을 가져옵니다..
	 * 
	 * @return 게시글 목록
	 */
	public Set<Board> getBoardSet() {
		return this.boardSet;
	}

	/**
	 * 지역 댓글 목록을 설정합니다..
	 * 
	 * @param replySet
	 *            지역 댓글 목록
	 */
	public void setReplySet(Set<Reply> replySet) {
		this.replySet = replySet;
	}

	/**
	 * 지역 댓글를 추가합니다..
	 * 
	 * @param reply
	 *            지역 댓글
	 */
	public void addReply(Reply reply) {
		this.replySet.add(reply);
	}

	/**
	 * 지역 댓글 목록을 가져옵니다..
	 * 
	 * @return 지역 댓글 목록
	 */
	public Set<Reply> getReplySet() {
		return this.replySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((mno == null) ? 0 : mno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Member other = (Member) obj;
		if (mno == null) {
			if (other.mno != null) {
				return false;
			}
		} else if (!mno.equals(other.mno)) {
			return false;
		}
		return true;
	}

}
